server:
  port: @server.port@
spring:
  boot:
    admin:
      url: http://localhost:@server.port@
      discovery:
        enabled: false
    routes:
      endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
    turbine:
      clusters: default
      location: turbine
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    enabled: false
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
management:
  security:
    enabled: false

